CREATE TABLE [dbo].[DEVISES](
	[DEVID] [dbo].[ID] NOT NULL,
	[DEVSYMBOLE] [varchar](3) NULL,
	[DEVLIBELLE] [varchar](20) NULL,
	[DEVCOURS] [numeric](18, 12) NULL,
	[DEVCOURSTARIF] [numeric](18, 12) NULL,
	[DEVNBDEC] [smallint] NULL,
	[DEVPARITE] [smallint] NULL,
	[DEVISACTIVE] [dbo].[BOOL] NULL,
	[DEVISREFERENCE] [dbo].[BOOL] NULL,
	[USRMODIF] [varchar](30) NULL,
	[DATECREATE] [datetime] NULL,
	[DATEUPDATE] [datetime] NULL,
	[DEVLIBELLEDIVISION] [varchar](20) NULL,
	[DEVCOURSINV] [numeric](18, 12) NULL,
CONSTRAINT [PK_DEVISES] PRIMARY KEY CLUSTERED ([DEVID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
CONSTRAINT [IX_DEVISES] UNIQUE NONCLUSTERED ([DEVSYMBOLE] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];
