CREATE TABLE [dbo].[DEVISES_HISTO](
	[DVHID] [dbo].[ID] IDENTITY(1,1) NOT NULL,
	[DEVID] [dbo].[ID] NOT NULL,
	[DVHDATEDEB] [datetime] NOT NULL,
	[DVHDATEFIN] [datetime] NOT NULL,
	[DVHCOURS] [numeric](18, 12) NULL,
	[USRMODIF] [varchar](30) NULL,
	[DATECREATE] [datetime] NULL,
	[DATEUPDATE] [datetime] NULL,
	[DVHCOURSINV] [numeric](18, 12) NULL,
CONSTRAINT [PK_DEVISES_HISTO] PRIMARY KEY CLUSTERED ([DVHID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]) 
ON [PRIMARY];
