CREATE TABLE [dbo].[exchange_rates_daily] (
    [rate_daily_id]   INT             IDENTITY (1, 1) NOT NULL,
    [currency]        NCHAR (3)       NOT NULL,
    [time_period]     DATE            NOT NULL,
    [series_key]      NVARCHAR (30)   NOT NULL,
    [freq]            NCHAR (1)       NULL,
    [currency_denom]  NCHAR (3)       NULL,
    [exr_type]        NCHAR (4)       NULL,
    [exr_suffix]      NCHAR (1)       NULL,
    [obs_value]       DECIMAL (18, 6) NULL,
    [obs_status]      NCHAR (1)       NULL,
    [obs_conf]        NVARCHAR (255)  NULL,
    [obs_pre_break]   NVARCHAR (255)  NULL,
    [obs_com]         NVARCHAR (255)  NULL,
    [time_format]     NVARCHAR (3)    NULL,
    [breaks]          NVARCHAR (255)  NULL,
    [collection_code] NCHAR (1)       NULL,
    [compiling_org]   NVARCHAR (255)  NULL,
    [diss_org]        NVARCHAR (255)  NULL,
    [dom_ser_ids]     NVARCHAR (255)  NULL,
    [publ_ecb]        NVARCHAR (255)  NULL,
    [publ_mu]         NVARCHAR (255)  NULL,
    [publ_public]     NVARCHAR (255)  NULL,
    [unit_index_base] NVARCHAR (8)    NULL,
    [compilation]     NVARCHAR (255)  NULL,
    [coverage]        NVARCHAR (255)  NULL,
    [decimals]        SMALLINT        NULL,
    [nat_title]       NVARCHAR (255)  NULL,
    [source_agency]   NCHAR (3)       NULL,
    [source_pub]      NVARCHAR (255)  NULL,
    [title]           NVARCHAR (255)  NULL,
    [title_compl]     NVARCHAR (255)  NULL,
    [unit]            NCHAR (3)       NULL,
    [unit_mult]       SMALLINT        NULL,
    CONSTRAINT [PK_exchange_rates_daily] PRIMARY KEY CLUSTERED ([currency] ASC, [time_period] ASC),
    CONSTRAINT [UQ_exchange_rate_daily] UNIQUE NONCLUSTERED ([currency] ASC, [series_key] ASC, [time_period] ASC),
    CONSTRAINT [FK_exchange_rate_daily_To_exchange_rates_series] FOREIGN KEY ([currency]) REFERENCES [exchange_rate_series]([currency])
);

